### PR TITLE
feat: ❇️  added moving and copying folders api

### PR DESCRIPTION
**Pull request by Aydawka**
- Added moving folders api: moves directory along with the files in it
- Added copying folders api: copies directory in the source and moves directory to the destination folder.

### CODE REVIEW

**Comment by Aydawka** [comment]
@megasanjay I have updated this branch. let me know please if anything else is needed

**Comment by megasanjay** [comment]
These endpoints should be in their own files

**Comment by Aydawka** [comment]
@megasanjay Since all endpoints are in the same destination, they were also located there. In that case I need to move them to other file since they are logically different from other endpoints?

**Comment by megasanjay** [comment]
The new file should probably be in the utils directory. Also does the move function not implement overwrite protections?

**Comment by Aydawka** [comment]
@megasanjay It does, if overwrite bool is false file can not be moved. If it is true then it will move to the new destination

**Review by megasanjay — APPROVED** [review]

**Pull request merged**
